name: setup-bazel-action
description: setup bazel in your actions workflow
author: romnnn
branding:
  icon: download-cloud
  color: white
inputs:
  version:
    description: bazel version to install
    required: false
    default: 3.7.2
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        ${{ github.action_path }}/setup-bazel.sh ${{ inputs.version }}
