name: test

on: ['push']

jobs:
  setup-bazel:
    strategy:
      matrix:
        # windows not supported at the moment, feel free to create a pull request
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: setup bazel
        uses: ./
        with:
          version: 3.7.1
        
      - name: run bazel command
        run: |
          bazel -h

  setup-bazel-clean:
    strategy:
      matrix:
        container: ['ubuntu:20.04', 'centos:8', 'debian:stable']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      # volumes: - ./:/action
    steps:
      - uses: actions/checkout@v2

      - name: setup bazel
        uses: romnnn/setup-bazel-action@master
        with:
          version: 3.7.1
        
      - name: run bazel command
        run: |
          bazel -h
